### ISSUE TITLE
Should we pin to a version of Bazel in CI?

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#101]
Currently we pin to a version of Bazel in CI.

Most projects in the bazelbuild org don't do this (a couple do, though). Some pin for specific configurations (e.g. to check support for a "minimum Bazel version").

The benefit of pinning is that we can opt-in to breakage in a particular PR. The downside is that we want to move quickly. A mitigating factor is that post-1.0 the intent is for Bazel to be reasonable about the pace of breaking changes.

**Comment by jrbeverly** [comment]
I'd prefer it if we didn't pin the version of bazel in CI at the moment. When the rules have reached (or close to) D2L generally usable, I'd be more in favour of pinning them.

If we pin the version now, we will need to wait for a version bump to identify any breaking changes (or deprecation notices). How frequently that occurs requires dependabot, or someone to be on top of updating bazel in CI.

Not pinning isn't without risks (such as a breaking change failing every pull request), but I'd be more confident with the rules if we were forced to always be at the latest version.

**Comment by j3parker** [comment]
Closing in favour of #155 which will allow us to mitigate the downsides of pinning.
