### ISSUE TITLE
Add support for .NET 5

### ISSUE THREAD

**Issue by jimevans** [Brightspace/rules_csharp#145]
.NET 5 has [officially been released](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) now. These rules should support it.

**Comment by j3parker** [comment]
Related: issue https://github.com/Brightspace/rules_csharp/issues/141 we need to better document how to do this.

The BUILD file for the framework (which imports the framework DLLs with the correct dependencies) needs to be regenerated. Unsurprisingly, the list of DLLs has changed:

```
$ comm -3 <(cd net5.0; ls) <(cd netcoreapp3.1; ls)
        System.Buffers.xml
        System.Diagnostics.Debug.xml
        System.Diagnostics.Tools.xml
System.Formats.Asn1.dll
System.Formats.Asn1.xml
System.Net.Http.Json.dll
System.Net.Http.Json.xml
        System.Resources.ResourceManager.xml
        System.Runtime.Extensions.xml
        System.Runtime.InteropServices.WindowsRuntime.dll
        System.Runtime.InteropServices.WindowsRuntime.xml
        System.Security.Principal.xml
        System.Threading.Tasks.xml
        System.Threading.Timer.xml
mscorlib.xml
```

**Comment by j3parker** [comment]
(I'll try to get to this today or tomorrow.)
