### ISSUE TITLE
Support compiling against .NET 4.0

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#40]
As mentioned in #39 we don't support compiling .NET 4.0 assemblies yet because of an issue with the BUILD-file generator.

Note that we do, however, support using .NET 4.0 assemblies via NuGet packages, etc. This is just about getting the framework DLLs wired into `@net`

**Comment by j3parker** [comment]
If we go too long without this we might want to remove .NET 4.0 entirely. We talked about yesterday how `@net`, being built on top of the same framework resolving logic as all the other DLLs it means that this:

```python
csharp_library(
    name = "Foo"
    target_frameworks = ["net40"],
    srcs = [ ... ],
    deps = ["@net//:System.Linq"],
)
```

Will end up compiling against `@net20//:System.Linq` instead which is unexpected.

If we remove support for `net40` entirely this will make it hard to use NuGet packages. Maybe we could just "hack" `import_multiframework_library` temporarily to behave weirdly around `net40`. Alternatively we could just fix .NET 4.0 in the near future.

**Comment by j3parker** [comment]
I guess `@net` is a liability (for the same reason) until we have full framework coverage anyway, so for the milestone we should just fix this.

**Comment by omsmith** [comment]
Yeah I don't think it will be hard by any particular stretch - I think it's just because for whatever reason the environment I'm running the generator in means the `net40` assemblies (at least the first one anyway) are already loaded so it can't load again.

Can probably solve that by getting my environment to be different, or catching the exception and saying "okay, i'll just use the already loaded one then"

**Comment by j3parker** [comment]
Maybe we should switch to using https://github.com/dotnet/corefxlab/blob/master/docs/specs/typeloader.md

I'm used to using reflection-only loads for this sort of stuff so that's what I did. It's pretty broken though, so they added something better in .NET Core, which doesn't involve literally loading the assembly into your app domain. If we wanted to open source the generator we'd need to switch to it anyway.

**Comment by omsmith** [comment]
Actually I was wrong about why `net40` wasn't loading, it just has every dll twice in the ReferenceAssemblies package.

**Comment by j3parker** [comment]
Alright, so this is probably not a separate thing then. Closing.
